### ISSUE TITLE
Traduzir texto

### ISSUE THREAD

**Issue by JoaoMonde** [eusoualec/eusoualec.github.io#10]
Todos os textos que indica um cadastro, estão em inglês.
Ex: #EUSOUALEC - CONHEÇA A ALEC - link direciona para um cadastro que o texto está em inglês.
Traduzir para o Português.

**Comment by esasse** [comment]
Você diz os botões da página Início? No meu caso eles não estão direcionando para nada. Ao clicar, nada acontece.

**Comment by esasse** [comment]
Vou fechar essa issue pois não consegui reproduzir.
