### ISSUE TITLE
Criar página Seja Voluntário

### ISSUE THREAD

**Issue by JoaoMonde** [eusoualec/eusoualec.github.io#15]
Alterar o ícone de acesso, onde está escrito seja voluntario e direciona para pagina de cadastro, alterar SEJA VOLUNTÁRIO para INSCREVA-SE

**Comment by MateusScapolan** [comment]
É necessário criar a página mostrando o trabalho dos voluntários, com o passo a passo para se tornar um.

**Comment by esasse** [comment]
Já está no ar.
