### ISSUE TITLE
Tornar a galeria de imagens dinâmica

### ISSUE THREAD

**Issue by JoaoMonde** [eusoualec/eusoualec.github.io#17]
Trocar as fotos que estão lá, por fotos do projeto.

**Comment by esasse** [comment]
Hoje a galeria é estática. Precisamos deixar ela dinâmica, pegando as fotos de uma pasta.

**Comment by esasse** [comment]
@martinusso você pretende concluir isso?

**Comment by ericoocampos** [comment]
Criei a galeria dinamica
