### ISSUE TITLE
Remover caixas de opção da página Sobre

### ISSUE THREAD

**Issue by MateusScapolan** [eusoualec/eusoualec.github.io#20]
Na página **Sobre** existem quatro quadros, iguais da página inicial, que precisam ser removidos.

**Comment by esasse** [comment]
Pq remover?

**Comment by MateusScapolan** [comment]
@esasse Na minha opinião não faz sentido repetir esses quatro quadros na página **Sobre**. Mas se for manter eles, precisa pelo menos remover o **Nossa Missão**, pois ele vai redirecionar pra essa mesma página.

![image](https://cloud.githubusercontent.com/assets/11272657/16766986/8bb3c6b6-4813-11e6-84ab-74f534662621.png)

**Comment by esasse** [comment]
Centralizando na issue #24
