### ISSUE TITLE
Inserir mapa de localização na página Contato

### ISSUE THREAD

**Issue by MateusScapolan** [eusoualec/eusoualec.github.io#21]
É necessário inserir na página de **Contato** a localização da associação utilizando o Google Maps.

`<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d963.7737536225313!2d-47.35612914899649!3d-22.713873109264544!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x94c89b73e22a7d51%3A0x73bea5c7d922fc04!2sR.+Serra+Formosa%2C+69+-+Parque+da+Liberdade%2C+Americana+-+SP%2C+13470-423!5e0!3m2!1spt-BR!2sbr!4v1468879830635" width="100%" height="350" frameborder="0" style="border:0" allowfullscreen></iframe>`

**Comment by MateusScapolan** [comment]
<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1038.2975449096782!2d-47.355960265402594!3d-22.71372377725547!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x94c89b715d2261a3%3A0x18d0ffd3e658d7e!2sR.+Serra+da+Boca%C3%ADna%2C+48+-+Parque+da+Liberdade%2C+Americana+-+SP%2C+13470-424!5e0!3m2!1spt-BR!2sbr!4v1468282295470" width="2400" height="350" frameborder="0" style="border:0" allowfullscreen></iframe>

**Comment by esasse** [comment]
A página de contato já tinha um código para mostrar mapa, mas não estava certo. Eu corrigi o código mas agora está dando outro erro: https://developers.google.com/maps/documentation/javascript/error-messages#missing-key-map-error

Depois vou testar esse código que você postou.

**Comment by ericoocampos** [comment]
Não funcionou com o Iframe também, apenas local.

**Comment by ericoocampos** [comment]
Não teve acordo. 

Removido mapa e inserido link no endereço
