### ISSUE TITLE
Colunas não fazem transição para texto no mobile

### ISSUE THREAD

**Issue by MateusScapolan** [eusoualec/eusoualec.github.io#23]
No navegador mobile, ao clicar sobre as colunas **Cata-Vento** e **Ação do Ano**, não é feita a transição mostrando o texto.

**Comment by esasse** [comment]
Isso eu não sei bem como vamos resolver. Esse bug também existe no template padrão @ericoocampos ? Eu não achei o site do template para fazer um teste.

**Comment by ericoocampos** [comment]
Funcionando!
