### ISSUE TITLE
Criar página Sobre

### ISSUE THREAD

**Issue by esasse** [eusoualec/eusoualec.github.io#24]
Página contando a história da associação em mais detalhes, possivelmente incluindo as fotos dos fundadores, etc.

Outras issues que existiam sobre esta página mas que estamos unificando aqui: #18 #20.

**Comment by esasse** [comment]
Vou pedir para eles enviarem um texto para a página.

**Comment by esasse** [comment]
Mandei e-mail para eles pedindo o texto.

**Comment by esasse** [comment]
@MateusScapolan coloque o texto revisado aqui assim que concluir.

**Comment by esasse** [comment]
[historia da alec.docx](https://github.com/eusoualec/eusoualec.github.io/files/383780/historia.da.alec.docx)

**Comment by MateusScapolan** [comment]
Separei o texto em quatro partes, História, Quem Somos, Equipe e O que significa ALEC.

Porém eu preciso verificar algumas informações sobre a história antes de finalizar.
- Confirmar "história do garotinho" no início;
- Quando realmente iniciou o projeto.

https://docs.google.com/a/monde.com.br/document/d/1NHniJHdqBX_fSB3hrFdrtNbPgY2smwjBmQC5WNHomdY/edit?usp=sharing

**Comment by ericoocampos** [comment]
http://eusoualec.org.br/sobre
