### ISSUE TITLE
Corrigir texto da página Contatos

### ISSUE THREAD

**Issue by MateusScapolan** [eusoualec/eusoualec.github.io#26]
Na página Contatos existe o texto:

Alec está de portas abertas. Fale conosco, venha nos visitar, faça parte do nosso sonho!

Ele pode ser melhorado

**A** Alec está de portas abertas. Fale conosco **e** venha nos visitar, faça parte do nosso sonho!

**Comment by esasse** [comment]
Boa sugestão! Quando for coisas simples assim, você mesmo pode editar o
arquivo usando a próprio interface web do GitHub, quer tentar?

2016-07-18 20:16 GMT-03:00 Mateus Eduardo Scapolan <notifications@github.com

**Comment by MateusScapolan** [comment]
Corrigido
