### ISSUE TITLE
Ao selecionar colunas não é feita a transição para o texto (iOS com Safari)

### ISSUE THREAD

**Issue by MateusScapolan** [eusoualec/eusoualec.github.io#33]
Ao clicar as colunas CATA-VENTO e AÇÃO DO ANO, no navegador Safari em dispositivos móveis, não aparece o texto como na versão desktop e nos navegadores do Android.

Esse problema foi resolvido, porém só funcionou para o android #23

**Comment by esasse** [comment]
No tema original também acontece, acho que não vale a pena quebrar muito a cabeça com isso neste momento: http://demo.ouarmedia.com/sadaka/
