### ISSUE TITLE
Criar endereço de e-mail com o domínio novo

### ISSUE THREAD

**Issue by MateusScapolan** [eusoualec/eusoualec.github.io#34]
E-mail para ser usado como endereço oficial da associação.

Sugestões:
contato@eusou..
faleconosco@eusou..
sac@eusou..

**Comment by esasse** [comment]
Também acho uma boa criar, mas para isso precisa treinar o povo lá para usar estas novas contas. Você quer fazer isso @MateusScapolan ?

**Comment by esasse** [comment]
@MateusScapolan como ficou isso? Conseguiu passar algo pra eles?

**Comment by MateusScapolan** [comment]
@esasse está bem parado o projeto e não estou conseguindo ajudar eles como eu tinha falado. Melhor outra pessoa assumir isso.

**Comment by esasse** [comment]
Eu falei com eles sobre isso e preferem ficar com o e-mail do Gmail mesmo, sem o domínio. Talvez no futuro a gente consiga explicar melhor para eles.
