### ISSUE TITLE
Remover formulário de contato

### ISSUE THREAD

**Issue by esasse** [eusoualec/eusoualec.github.io#7]
O formulário de contato padrão do tema precisa de PHP para funcionar e o GitHub Pages não suporta.

Acho que o mais simples neste momento é remover o formulário e deixar apenas o e-mail direto para contato.

**Comment by ericoocampos** [comment]
Inserido e-mail para contato no footer e removido formulário

**Comment by esasse** [comment]
Na página de contato ainda tem um formulário.
